image:
  repository: ghcr.io/crazy-max/cloudflared
  tag: 2022.1.0
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  annotations: {}
  labels: {}

service:
  enabled: true
  type: ClusterIP
  annotations: {}
  labels: {}

env:
  - name: TZ
    value: UTC
  - name: TUNNEL_DNS_UPSTREAM
    value: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query

ports:
  dns:
    enabled: true
    port: 5053
    nodePort: null
    protocol: UDP
  dnstcp:
    enabled: true
    port: 5053
    nodePort: null
    protocol: TCP
  metrics:
    enabled: false
    port: 49312
    nodePort: null

serviceAccount:
  name: ''

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
