{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflared.fullname" . }}-metrics
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.ports.metrics.enabled }}
    - name: metrics
      port: {{ .Values.ports.metrics.port }}
      targetPort: 49312
      {{- if and (eq $.Values.service.type "NodePort") .Values.ports.metrics.nodePort }}
      nodePort: {{ .Values.ports.metrics.nodePort }}
      {{- end }}
      protocol: "TCP"
    {{- end }}
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
{{- end }}
